name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        mode: ["Release"]
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install NuGet client
      uses: nuget/setup-nuget@v1
    - name: Restore NuGet packages
      run: |
        nuget restore ProcessLimiter.csproj
    - name: Build
      shell: cmd
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" ProcessLimiter.csproj /p:Configuration=${{ matrix.mode }}
    - name: Upload
      if: contains(matrix.mode, 'Release')
      uses: actions/upload-artifact@master
      with:
        name: ProcessLimiter
        path: .\bin\Release\
